version: '3'

services:
    coordinator:
        container_name: coordinator
        image: golang:1.12
        ports:
            - 8080:80
        volumes:
            - ./coordinator:/go/src/coordinator
        environment:
            - GO111MODULE=on
        working_dir: /go/src/coordinator
        networks:
            - dis_sys_network
        command: ./bin/coordinator

    counter:
        image: golang:1.12
        volumes:
            - ./counter:/go/src/counter
        environment:
            - GO111MODULE=on
        working_dir: /go/src/counter
        networks:
            - dis_sys_network
        expose:
            - 80
        depends_on:
            - coordinator
        command: ./bin/counter

volumes:
    dis_sys_volumes:
        driver: local

networks:
    dis_sys_network:
        driver: bridge
